######################################################################
# Automatically generated by qmake (3.0) seg nov 21 09:48:37 2016
######################################################################

TEMPLATE = app
TARGET = operation

QT += quick quickcontrols2 widgets \
qml multimedia

INCLUDEPATH += .

# Input
SOURCES += main.cpp

OTHER_FILES += \
    main.qml

RESOURCES += \
    operation.qrc
