######################################################################
# Automatically generated by qmake (3.0) Sun Nov 20 18:44:59 2016
######################################################################
TEMPLATE = app
TARGET = operation

QT += quick quickcontrols2 widgets

INCLUDEPATH += .

# Input
SOURCES += main.cpp

OTHER_FILES += \
    main.qml 

RESOURCES += \
    operation.qrc