#############################################################################
# Makefile for building: operation.app/Contents/MacOS/operation
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  geo-app-operation.pro
# Template: app
# Command: /Users/ronaldo/Library/Qt/5.7/clang_64/bin/qmake -o Makefile geo-app-operation.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../../../Library/Qt/5.7/clang_64/lib/QtQuickControls2.framework/Headers -I../../../Library/Qt/5.7/clang_64/lib/QtQuick.framework/Headers -I../../../Library/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I../../../Library/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I../../../Library/Qt/5.7/clang_64/lib/QtQml.framework/Headers -I../../../Library/Qt/5.7/clang_64/lib/QtNetwork.framework/Headers -I../../../Library/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Library/Qt/5.7/clang_64/mkspecs/macx-clang -F/Users/ronaldo/Library/Qt/5.7/clang_64/lib
QMAKE         = /Users/ronaldo/Library/Qt/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = operation1.0.0
DISTDIR = /Users/ronaldo/Dev/qt5/geo-app-operation/.tmp/operation1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/ronaldo/Library/Qt/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/ronaldo/Library/Qt/5.7/clang_64/lib -framework QtQuickControls2 -framework QtQuick -framework QtQml -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework QtGui -framework QtWidgets -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_operation.cpp
OBJECTS       = main.o \
		qrc_operation.o
DIST          = ../../../Library/Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../../Library/Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../../Library/Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../../Library/Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../Library/Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../Library/Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Library/Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../../Library/Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../Library/Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/lex.prf \
		geo-app-operation.pro  main.cpp
QMAKE_TARGET  = operation
DESTDIR       = 
TARGET        = operation.app/Contents/MacOS/operation


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d operation.app/Contents/MacOS/ || mkdir -p operation.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: geo-app-operation.pro ../../../Library/Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../../../Library/Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../../Library/Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../../Library/Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../../Library/Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../Library/Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../Library/Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Library/Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../../Library/Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../Library/Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../Library/Qt/5.7/clang_64/mkspecs/features/lex.prf \
		geo-app-operation.pro \
		operation.qrc \
		../../../Library/Qt/5.7/clang_64/lib/QtQuickControls2.framework/QtQuickControls2.prl \
		../../../Library/Qt/5.7/clang_64/lib/QtQuick.framework/QtQuick.prl \
		../../../Library/Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../Library/Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Library/Qt/5.7/clang_64/lib/QtQml.framework/QtQml.prl \
		../../../Library/Qt/5.7/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		../../../Library/Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile geo-app-operation.pro
../../../Library/Qt/5.7/clang_64/mkspecs/features/spec_pre.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/qdevice.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/features/device_config.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/common/unix.conf:
../../../Library/Qt/5.7/clang_64/mkspecs/common/mac.conf:
../../../Library/Qt/5.7/clang_64/mkspecs/common/macx.conf:
../../../Library/Qt/5.7/clang_64/mkspecs/common/sanitize.conf:
../../../Library/Qt/5.7/clang_64/mkspecs/common/gcc-base.conf:
../../../Library/Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Library/Qt/5.7/clang_64/mkspecs/common/clang.conf:
../../../Library/Qt/5.7/clang_64/mkspecs/common/clang-mac.conf:
../../../Library/Qt/5.7/clang_64/mkspecs/qconfig.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Library/Qt/5.7/clang_64/mkspecs/features/qt_functions.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/qt_config.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Library/Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/default_pre.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/resolve_config.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/default_post.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/warn_on.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/qt.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/resources.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/moc.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/uic.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/unix/thread.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/file_copies.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/mac/rez.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/exceptions.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/yacc.prf:
../../../Library/Qt/5.7/clang_64/mkspecs/features/lex.prf:
geo-app-operation.pro:
operation.qrc:
../../../Library/Qt/5.7/clang_64/lib/QtQuickControls2.framework/QtQuickControls2.prl:
../../../Library/Qt/5.7/clang_64/lib/QtQuick.framework/QtQuick.prl:
../../../Library/Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../Library/Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Library/Qt/5.7/clang_64/lib/QtQml.framework/QtQml.prl:
../../../Library/Qt/5.7/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
../../../Library/Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile geo-app-operation.pro

qmake_all: FORCE

operation.app/Contents/PkgInfo: 
	@test -d operation.app/Contents || mkdir -p operation.app/Contents
	@$(DEL_FILE) operation.app/Contents/PkgInfo
	@echo "APPL????" > operation.app/Contents/PkgInfo
operation.app/Contents/Resources/empty.lproj: 
	@test -d operation.app/Contents/Resources || mkdir -p operation.app/Contents/Resources
	@touch operation.app/Contents/Resources/empty.lproj
	
operation.app/Contents/Info.plist: 
	@test -d operation.app/Contents || mkdir -p operation.app/Contents
	@$(DEL_FILE) operation.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.operation,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,operation,g" -e "s,@LIBRARY@,operation,g" -e "s,@TYPEINFO@,????,g" ../../../Library/Qt/5.7/clang_64/mkspecs/macx-clang/Info.plist.app >operation.app/Contents/Info.plist

all: Makefile \
		operation.app/Contents/PkgInfo \
		operation.app/Contents/Resources/empty.lproj \
		operation.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents operation.qrc $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r operation.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_operation.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_operation.cpp
qrc_operation.cpp: operation.qrc \
		../../../Library/Qt/5.7/clang_64/bin/rcc \
		qtquickcontrols2.conf \
		main.qml \
		images/menu@3x.png \
		images/menu.png \
		images/drawer.png \
		images/drawer@4x.png \
		images/file.svg \
		images/menu@2x.png \
		images/videocam.png \
		images/drawer@3x.png \
		images/drawer@2x.png \
		images/menu@4x.png
	/Users/ronaldo/Library/Qt/5.7/clang_64/bin/rcc -name operation operation.qrc -o qrc_operation.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean 

####### Compile

main.o: main.cpp ../../../Library/Qt/5.7/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		../../../Library/Qt/5.7/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Library/Qt/5.7/clang_64/lib/QtQml.framework/Headers/QQmlApplicationEngine \
		../../../Library/Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		../../../Library/Qt/5.7/clang_64/lib/QtQml.framework/Headers/QQmlContext \
		../../../Library/Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlcontext.h \
		../../../Library/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../../Library/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		../../../Library/Qt/5.7/clang_64/lib/QtQuickControls2.framework/Headers/QQuickStyle \
		../../../Library/Qt/5.7/clang_64/lib/QtQuickControls2.framework/Headers/qquickstyle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_operation.o: qrc_operation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_operation.o qrc_operation.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

